# Generated by Django 5.1 on 2026-02-20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessingRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("RUNNING", "Running"), ("DONE", "Done"), ("FAILED", "Failed")],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("input_path", models.CharField(max_length=1000)),
                ("uploaded_file", models.FileField(blank=True, null=True, upload_to="uploads/")),
                ("batch_size", models.PositiveIntegerField(default=10000)),
                ("slow_threshold", models.PositiveIntegerField(default=200)),
                ("status_code", models.PositiveIntegerField(default=500)),
                ("workers", models.PositiveIntegerField(default=1)),
                ("profile", models.BooleanField(default=False)),
                ("total_lines", models.BigIntegerField(default=0)),
                ("bad_lines", models.BigIntegerField(default=0)),
                ("total_500", models.BigIntegerField(default=0)),
                ("total_slow", models.BigIntegerField(default=0)),
                ("top_url_500", models.CharField(blank=True, max_length=2000, null=True)),
                ("top_url_500_count", models.BigIntegerField(default=0)),
                ("top_url_slow", models.CharField(blank=True, max_length=2000, null=True)),
                ("top_url_slow_count", models.BigIntegerField(default=0)),
                ("duration_seconds", models.FloatField(default=0.0)),
                ("metrics_json", models.JSONField(blank=True, default=dict)),
                ("profile_stats_path", models.CharField(blank=True, max_length=1000, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
