# Generated by Django 5.2.11 on 2026-02-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_processingrun_status_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processingrun",
            name="input_path",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
    ]
